import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FRC Next Gen Stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="fixed top-0 left-0 right-0 z-50 bg-[#1a202c] border-b border-gray-800">
          <div className="max-w-7xl mx-auto px-6">
            <div className="flex items-center justify-between h-16">
              {/* Logo/Brand */}
              <div className="flex items-center gap-3">
                <span className="text-xl font-semibold text-white tracking-tight">FRC Next Gen Stats</span>
              </div>

              {/* Navigation Links */}
              <div className="flex items-center gap-8">
                <a href="/" className="text-gray-300 hover:text-white transition-colors duration-200 text-sm font-medium">Home</a>
                <a href="/stats" className="text-gray-300 hover:text-white transition-colors duration-200 text-sm font-medium">Stats</a>
              </div>
            </div>
          </div>
        </nav>
        <div>
          {children}
        </div>

  
        <footer className="fixed bottom-0 left-0 right-0 z-50 bg-blue-950 border-t border-gray-800">
          <div className="max-w-7xl mx-auto px-6 py-3">
            <div className="flex items-center justify-center gap-2 text-sm text-gray-400">
              <span>Powered by</span>
              <a
                href="https://www.thebluealliance.com"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-2 text-sky-400 hover:text-sky-300 transition-colors duration-200 font-medium"
              >
                The Blue Alliance
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
